config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'home#index'

  resources :registers
  resources :objectives
  resources :photos
  resources :medals
end

app/models/register.rb
class Register < ActiveRecord::Base
  include Concerns::Badges

  belongs_to :user
  scope :oldest, -> { order('registers.measured_at desc') }
  scope :newest, -> { order('registers.measured_at asc') }

  validates :measured_at, presence: true
  validates :weight, presence: true
  validate :measured_at_cannot_be_repeated, on: :create

  has_many :photos, as: :assetable, class_name: 'Photo', dependent: :destroy

  def previous
    user.registers.oldest.where('id < ?', id).first
  end

  def weight_diff
    return if previous.blank?
    (weight - previous.weight).to_f2
  end

  def diff_direction(diff)
    if diff > 0
      'up'
    elsif diff < 0
      'down'
    else
      'stable'
    end
  end

  def imc
    imc_calc.to_f2
  end

  def imc_calc
    ((1.72 * weight) / (user.height ** 3.06))
  end

  def imc_calc_old
    (weight / (user.height ** 2))
  end

  def imc_diff
    return if previous.blank?
    @imc_diff ||= (imc - previous.imc).to_f2
  end

  def measured
    measured_at.strftime(I18n.t('date.formats.minimum'))
  end

  private

  def measured_at_cannot_be_repeated
    if user.registers.where(measured_at: measured_at).exists?
      errors.add :measured_at, 'Only 1 date allowed for register'
    end
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  def index
    @registers = current_user.registers.oldest.page(params[:page])
    @register = Register.new
  end

  def create
    @register = current_user.registers.new(register_params)
    if @register.save
      redirect_to root_path, notice: 'Registro adicionado com sucesso.'
    else
      redirect_to root_path, notice: @register.errors.full_messages
    end
  end

  def update
    register = current_user.registers.find(params[:id])
    if register.update(register_params)
      render json: register
    else
      render json: { errors: register.errors.full_messages }
    end
  end

  def destroy
    register = current_user.registers.find(params[:id])
    if register.destroy
      redirect_to registers_path, notice: 'Registro removido com sucesso.'
    else
      redirect_to registers_path, notice: register.errors.full_messages
    end
  end

  def graph
  end

  private

  def register_params
    params.require(:register).permit(:measured_at, :weight, :offday, :workout, :note)
  end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_add.html.haml
= form_for @register, html: { class: 'form-inline' } do |f|
  .form-group
    .input-group
      .input-group-addon Data
      = f.text_field :measured_at, required: true, class: 'form-control datepicker'
  .form-group
    .input-group
      .input-group-addon Peso
      = f.text_field :weight, size: 5, maxlength: 5, required: true, class: 'form-control'
      .input-group-addon Kg
  = f.button 'Adicionar', type: 'submit', class: 'btn btn-primary'

app/views/registers/_modal.html.haml
.modal.fade#addNote
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title Adicione notas sobre esse registro:
      .modal-body
        %textarea{class: 'form-control', rows: 12, placeholder: 'Nenhuma anotação foi feita ainda.'}
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Fechar
        %button.btn.btn-primary.btn-save{:type => "button"} Salvar

app/views/registers/_register.html.haml
%tr
  %td= l register.measured_at
  %td= l register.measured_at, format: :weekday
  %td= register.weight.to_s << ' Kg'
  %td= imc register.weight, register.user.height
  %td
    - if register.weight_diff.present?
      %span{:class => "m-#{register.diff_direction(register.weight_diff)}"}
        = register.weight_diff.to_s << ' Kg'
  %td
    - if register.imc_diff.present?
      %span{:class => "m-#{register.diff_direction(register.imc_diff)}"}
        = register.imc_diff
  %td
    = check_box_tag :objective, :offday, register.offday, class: 'offday update-register', data: { url: register_path(register) }
  %td
    = check_box_tag :objective, :workout, register.workout, class: 'workout update-register', data: { url: register_path(register) }
  - if defined?(notable)
    %td= link_to 'Anotações', '#', data: { toggle: 'modal', target: '#addNote', note: register.note, id: register.id }, class: "register-#{register.id}"
  - if defined?(deletable)
    %td= link_to 'Apagar', register_path(register), method: :delete, data: { confirm: 'Tem certeza de que deseja apagar o registro?' }

app/views/registers/graph.html.haml
%h1 Registers#graph
%p Find me in app/views/registers/graph.html.erb

app/views/registers/index.html.haml
%h1 Registros de Peso
%hr/
%h3 Adicionar novo registro de peso
= render partial: "registers/add"
%hr/
- if @registers.blank?
  %p Não há registros.
- else
  = render partial: 'modal'
  %table.table
    %thead
      %tr
        %th Medido em
        %th Dia
        %th Peso
        %th
          %span{"data-toggle" => "tooltip", :title => "Índice de Massa Corporal"} IMC
        %th
          %span{"data-toggle" => "tooltip", :title => "Diferença ao Peso do dia Anterior"} DAP
        %th
          %span{"data-toggle" => "tooltip", :title => "Diferença ao IMC do dia Anterior"} DAI
        %th
          %span{"data-toggle" => "tooltip", :title => "OFF: Dia fora da Dieta"} OFF
        %th
          %span{"data-toggle" => "tooltip", :title => "WORKOUT: Você se exercitou hoje"} WORKOUT
        %th
        %th
    %tbody
      = render partial: "registers/register", collection: @registers, locals: { deletable: true, notable: true }
= paginate @registers