config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'home#index'

  resources :registers
  resources :objectives
  resources :photos
  resources :medals
end

app/models/objective.rb
class Objective < ActiveRecord::Base
  include Concerns::Math

  belongs_to :user
  belongs_to :register

  validates :title, presence: true
  validates :user, presence: true
  validates :register, presence: true
  validates :goal_at, presence: true
  validates :weight_goal, presence: true

  scope :completed, -> { where.not(weight_final: nil) }

  def completed?
    weight_final.present?
  end

  def days_missing
    (goal_at - Date.today).to_i
  end

  def days_passed
    (Date.today - register.measured_at).to_i
  end

  def initial_days_missing
    (goal_at - register.measured_at).to_i
  end

  def weight_missing
    (user.weight - weight_goal).to_f2
  end

  def weight_lost
    (register.weight - user.weight).to_f2
  end

  def weight_to_loss
    (register.weight - weight_goal).to_f2
  end

  def daily_weight_to_loss
    (weight_to_loss / days_missing).to_f2
  end

  def weight_expectative_in_days
    return 0.0 if daily_weight <= 0
    (weight_missing / daily_weight).to_i
  end

  def daily_weight
    return 0.0 if weight_lost <= 0
    (weight_lost / days_passed).to_f2
  end

  def percentage_of_loss
    (weight_lost / weight_to_loss * 100).to_f2
  end

  def daily_weight_diff
    return 0.0 if daily_weight <= 0
    percentage_between daily_weight_to_loss, daily_weight
  end
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  def index
    @objectives = current_user.objectives.page(params[:page])
    @objective = Objective.new
  end

  def create
    @objective = current_user.objectives.new(objective_params)
    if @objective.save
      redirect_to objectives_path, notice: 'Objetivo criado com sucesso.'
    else
      render :index, alert: @objective.errors.full_messages
    end
  end

  def show
  end

  def new
  end

  def edit
  end

  private

  def objective_params
    params.require(:objective).permit(
      :title,
      :description,
      :register_id,
      :weight_goal,
      :goal_at
    )
  end
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/views/objectives/_form.html.haml
= form_for @objective do |f|
  .row
    .col-md-6
      .form-group
        = f.label :title
        = f.text_field :title, required: true, class: 'form-control'
      .form-group
        = f.label :description
        = f.text_area :description, class: 'form-control', rows: 6
    .col-md-6
      .form-group
        = f.label :register_id, 'Ponto de Partida'
        = f.select :register_id, current_user.registers.newest.map { |r| [l(r.measured_at), r.id] }, {}, required: true, class: 'form-control'
        %p.help-block Selecione um registro como ponto de partida.
      .form-inline
        %h3 Meta
        .form-group
          .input-group
            .input-group-addon Peso
            = f.text_field :weight_goal, size: 5, maxlength: 5, required: true, class: 'form-control'
            .input-group-addon Kg
        .form-group
          .form-group
            .input-group
              .input-group-addon Data
              = f.text_field :goal_at, required: true, class: 'form-control datepicker'
      %br.clear-all/
      .form-group
        = f.button 'Adicionar', type: 'submit', class: 'btn btn-primary'

app/views/objectives/_objective.html.haml
%tr
  %td= objective.title
  %td= l objective.goal_at
  %td= objective.weight_goal.to_s << ' Kg'
  %td= objective.completed? ? '---' : objective.days_missing.to_s << ' dias'
  %td= objective.weight_missing.to_s << ' Kg'
  %td= objective.daily_weight.to_s << ' Kg'
  %td= link_to 'Visualizar', objective_path(objective)
  %td= link_to 'Editar', edit_objective_path(objective)
  %td= link_to 'Apagar', objective_path(objective), method: :delete, data: { confirm: 'Tem certeza de que deseja apagar o registro?' }

app/views/objectives/edit.html.haml
%h1 Objectives#edit
%p Find me in app/views/objectives/edit.html.erb

app/views/objectives/index.html.haml
%h1 Objetivos
%p
  Objetivos são metas em prazos médios ou longos, do seu alcance desejado de peso. Como a plataforma é simples, apenas o acompanhamento diário da perda de peso, não é aconselho esperar resultados sobre o IMC.
  %br/
  A contagem de peso e perda do sistema Vai Vendo! é calculada diariamente, então as expectativas serão sempre diárias. Aconselhamos evitar objetivos maiores que seis meses.
%hr/
%h3 Seus objetivos
- if @objectives.blank?
  %p Não há registros.
- else
  %table.table
    %thead
      %tr
        %th Título
        %th Data da Meta
        %th Peso
        %th Tempo Restante
        %th Peso que falta
        %th
          %span{"data-toggle" => "tooltip", :title => "Média de Peso Diário"} MPD
        %th
        %th
    %tbody
      = render partial: "objective", collection: @objectives
= paginate @objectives if @objectives.present?
%hr/
%h3 Adicione um novo objetivo
= render partial: "form"

app/views/objectives/new.html.haml
%h1 Objectives#new
%p Find me in app/views/objectives/new.html.erb

app/views/objectives/show.html.haml
%h1 Objectives#show
%p Find me in app/views/objectives/show.html.erb