config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'home#index'

  resources :registers
  resources :objectives
  resources :photos
  resources :medals
end

app/views/shared/_footer.html.haml
%br/
%br/
%hr/
.container.text-center.initialism
  Vai Vendo App - Desenvolvido por Leonardo (Dante) Pereira -
  %a{:href => "http://www.leonardopereira.com", :target => "_blank"} www.leonardopereira.com
  \-
  %a{:href => "http://github.com/dantetekanem", :target => "_blank"} github.com/dantetekanem
%br/
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69214732-1', 'auto');
  ga('send', 'pageview');

app/views/shared/_line_graph.html.haml
%canvas#canvas
- if current_user.objective.present?
  :javascript
    jQuery(document).ready(function($){
      var data = {
        labels: #{raw(current_user.to_graph_dates.to_json)},
        datasets: [
          {
            label: "Peso",
            fillColor: "rgba(151,187,205,0.2)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",
            data: #{current_user.to_graph_registers.to_json}
          },
          {
            label: "Expectativa",
            fillColor: "rgba(20,20,20,0)",
            strokeColor: "rgba(20,20,20,0.8)",
            pointColor: "rgba(20,20,20,0.8)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(20,20,20,0.8)",
            data: #{current_user.to_graph_expect(current_user.reverse_registers.first, current_user.to_graph_registers.size).to_json}
          }
        ]
      }
      var myNewChart = new Chart($("#canvas").get(0).getContext("2d")).Line(data);
    })
- else
  :javascript
    jQuery(document).ready(function($){
      var data = {
        labels: #{raw(current_user.to_graph_dates.to_json)},
        datasets: [
          {
            label: "Peso",
            fillColor: "rgba(151,187,205,0.5)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",
            data: #{current_user.to_graph_registers.to_json}
          }
        ]
      }
      var myNewChart = new Chart($("#canvas").get(0).getContext("2d")).Line(data);
    })

app/views/shared/_medal.html.haml
.panel.panel-default
  .panel-heading.text-center
    %h3.panel-title
      PARABÉNS! Você recebeu uma medalha. :)
  .panel-body.text-center
    = image_tag("badges/#{ medal.name }.png")
    %p= medal.description
- medal.viewed!

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Vai Vendo!', root_path, class: 'navbar-brand'
    #navbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li{class: "#{nav_menu_active('objectives')}"}= link_to 'Objetivos', objectives_path
          %li{class: "#{nav_menu_active('registers')}"}= link_to 'Registros de Peso', registers_path
          %li{class: "#{nav_menu_active('photos')}"}= link_to 'Fotos e Evolução', photos_path
          %li{class: "#{nav_menu_active('medals')}"}= link_to 'Medalhas', medals_path
          %li{class: "#{nav_menu_active('registrations')}"}= link_to 'Editar Perfil', edit_user_registration_path
          %li= link_to 'Sair', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Cadastrar-se', new_user_registration_path
          %li= link_to 'Logar-se', new_user_session_path
    / /.nav-collapse

app/views/shared/_register_today.haml
.container
  .row
    .col-md-6
      %h2
        %span.label.label-warning Você ainda não registrou o seu peso de hoje!
    .col-md-6.registration-today
      = form_for Register.new, html: { class: 'form-inline' } do |f|
        = f.hidden_field :measured_at, value: Date.today
        .form-group
          .input-group
            .input-group-addon Peso
            = f.text_field :weight, size: 5, maxlength: 5, required: true, class: 'form-control'
            .input-group-addon Kg
        = f.button 'Adicionar', type: 'submit', class: 'btn btn-primary'
  %hr/